### ISSUE TITLE
Add Support to Android

### ISSUE THREAD

**Issue by rogerluan** [rogerluan/arkana#1]

**Comment by AF-cgi** [comment]
What's the current status of it?

**Comment by rogerluan** [comment]
Hi @AF-cgi 👋 thank you for your interest in Android support!

Unfortunately I haven't had time to dedicate to this project as much as I could, and don't plan to add Android support on my own. Any contributions to this would be awesome and I'd truly appreciate if someone could implement it and open a PR 🙌

I'm open to share any info needed about the project with anyone interested in implementing this 🙇‍♂️

**Comment by mrea1** [comment]
I'm interested in contributing on the Android side. I'm busy for the next few weeks, but free after that

**Comment by rogerluan** [comment]
Android support has been released in [Arkana v2.0.0](https://github.com/rogerluan/arkana/releases/tag/v2.0.0)! 🚀  

Thank you to everyone involved, especially @husseinala ! 🙌
