### ISSUE TITLE
license compatibility issue: `colorize`

### ISSUE THREAD

**Issue by pavelmarchuk** [rogerluan/arkana#26]
Hi,

Would it be possible to replace `colorize` dependency with something else (`rainbow` or other gem)? `Colorize` uses GPL2 license and that may not be fully compatible with `Arkana`'s license.

Similar issue with `colorize` - https://github.com/spree/deface/issues/153

Thanks,

**Comment by rogerluan** [comment]
Hi @pavelmarchuk ! 

Thanks for bringing this up, I have no issues with changing this dependency. I'll take a closer look as soon as I can 🙏

**Comment by rogerluan** [comment]
Thanks for this suggestion @pavelmarchuk , the change has been merged to master and release in https://github.com/rogerluan/arkana/releases/tag/v1.3.1 💪 Let me know if there's anything else I can help you with!
