### ISSUE TITLE
The key is getting corrupted when it contains '$'

### ISSUE THREAD

**Issue by pavelmarchuk** [rogerluan/arkana#28]
The key is getting corrupted if it contains `$`.

I store `APIKeyStaging="A$QEsdXNWTK0Qc+iSAl"` in .env file, generate code and then I see "A+iSAl" as a decrypted value at the runtime.

Arkana v1.3.1.

Are there other special symbols that could corrupt keys?

**Comment by rogerluan** [comment]
Thank you so much for identifying and reporting this issue @pavelmarchuk 🙏 

I am unaware of other symbols that could interfere with the encryption process, but I will have a look and report back. If you have any new findings meanwhile, let me know! I'll think of ways to mitigate the problem with "problematic" characters

**Comment by rogerluan** [comment]
@pavelmarchuk I've opened a PR clarifying usage of special characters 💪 https://github.com/rogerluan/arkana/pull/30

Thanks again for bringing up this topic! 🚀

**Comment by pavelmarchuk** [comment]
Thanks for the explanation!
