### ISSUE TITLE
Arkana fails on CI due to .env file missing, even when env vars are all present in CI

### ISSUE THREAD

**Issue by rogerluan** [rogerluan/arkana#33]
### Discussed in https://github.com/rogerluan/arkana/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **mishaherasimov** March 17, 2023</sup>
I'm currently trying to build a pipeline that creates keys before building the project. 
I've imported all keys as environmental variables of the project.

Given these conditions, Arkana fails to generate an SPM package because .env is added to .gitignore.
What would be the correct way to configure Arkana?

CI Environment: Circle CI

<img width="845" alt="Screenshot 2023-03-17 at 2 46 38 PM" src="https://user-images.githubusercontent.com/20767940/225992079-96b3f8c8-deeb-4679-8fd0-574657e65a8c.png">
</div>

**Comment by vijaytholpadi** [comment]
@rogerluan Can I check if there is a plan to resolve this sometime?

Considering Arkana for key storage as part of Tuist adoption. I see good potential for usage of Arkana with Tuist as the former requires to move off CocoaPods to make the best use of the optimisations if offers.

Thanks for building Arkana!

**Comment by rogerluan** [comment]
Sorry I completely missed this message of yours @vijaytholpadi ! 

I haven't really received other reports of this issue, and I couldn't reproduce it either (I run Arkana on CI without a problem, using env vars and not local dotenv files while in CI), so this issue might not exist anymore. I assume you're just scanning through the open issues before deciding to try it out or not, and that's a super valid thing to do. But yeah my conclusion here is that this is a non-issue.

If you or someone else can confirm this has been fixed, I can go ahead and close this issue! I have tested this under Bitrise CI, by the way, but it should work the same way for every CI provider.

Thanks for the kind words! ❤️

**Comment by rogerluan** [comment]
cc @mishaherasimov perhaps you could chime in 😊 ? Do you still have this issue? Totally fair if you simply abandoned when faced that issue and didn't come back to it though, I wouldn't blame you 😢 sorry for taking so long to revisit this issue and report back

**Comment by mishaherasimov** [comment]
I'm still using version `1.4.0`. I'll bump up to the latest version tomorrow and reply in this thread.

**Comment by mishaherasimov** [comment]
@rogerluan based on my checks today, the problem is resolved. Values are being sourced from the environment correctly.

**Comment by rogerluan** [comment]
Amazing! Thanks for confirming @mishaherasimov! 🤗

**Comment by rogerluan** [comment]
I'm closing this issue then and the Discussion (the other link) as well.

@vijaytholpadi let me know if you still have any concerns, happy to discuss them! 😊 

Thanks everyone!
