### ISSUE TITLE
SPM fails to install this project (Package.swift doesn't exist)

### ISSUE THREAD

**Issue by houmie** [rogerluan/arkana#36]
Sorry for adding a screenshot, instead of pasting the error message. But Xcode doesn't allow me to copy it.

Essentially Package.swift can't be found.

<img width="974" alt="Screenshot 2023-06-25 at 17 03 23" src="https://github.com/rogerluan/arkana/assets/1832933/3d6603a8-c0d6-4672-9be6-5fe0f79ec575">

Thanks

**Comment by houmie** [comment]
Ahh sorry. I just noticed the installation via SPM for this project requires extra steps. Please allow me to do that and I come back to this issue to close it. Thanks

**Comment by houmie** [comment]
Yes, it works when I add it locally. Sorry for the false alarm. However there is a new issue when adding this to additional targets.

**Comment by houmie** [comment]
Yes, it was thank you.  I wanted to switch from Pods to SPM, and the cocoa-keys project was no longer an option.  So your project was perfect for it.  It works fine, great job.

**Comment by rogerluan** [comment]
I'm glad to hear it! 🎉
