### ISSUE TITLE
[Request] Support both Swift and ObjC

### ISSUE THREAD

**Issue by nelson-dai-17Live** [rogerluan/arkana#40]
Hi there,

I've tried Arkana recently, and it seems to support only Swift.
I considered writing an Obj-C wrapper, but it's impractical since the number of `Keys` is dynamic, I have to update the Obj-C wrapper every time when the number of Keys changes.

So I'd like to request an improvement that the generated codes support both Swift and ObjC.

**Comment by rogerluan** [comment]
Hi @nelson-dai-17Live 👋 

I appreciate your input, but I don't plan to add Objective-C support to Arkana. Sorry.

If you're keen, you can try https://github.com/orta/cocoapods-keys, which I know supports Objective-C, but it doesn't support SPMs (if you want to use them).

I hope this helps!
